### ISSUE TITLE
对一些接口签名貌似无效

### ISSUE THREAD

**Issue by sminder** [XGSClear7/fuck_dy#4]
hi，在测试https://api5-core-c-hl.amemv.com/aweme/v1/user/profile/接口的时候，好像签名无效

另外看到此处，好像有点问题
```
            result.append( hex(inputBytes[i+32])+'')[6:]
```
https://github.com/XGSClear7/fuck_dy/blob/e557963d31cb93807e2755b6645371e2d09f64df/fuck_douyin.py#L161

**Comment by XGSClear7** [comment]
这个解密可能已经被和谐了，你可以试用11.0以下版本的抖音做测试。

**Comment by XGSClear7** [comment]
此种破解方法仅提供参考，最稳妥的方法还是去调用底层so加密文件，可以去搜一下如何利用andserver搭建一个调用so文件的安卓app。

**Comment by sminder** [comment]
好的，多谢~ 稳妥的已经存在了，主要是想在服务器上部署会更稳定。另外，也想学一下so逆向的方法

**Comment by github-gsjb** [comment]
> 此种破解方法仅提供参考，最稳妥的方法还是去调用底层so加密文件，可以去搜一下如何利用andserver搭建一个调用so文件的安卓app。

楼主，请问有联系方式吗？我是逆向的，找到这个so，有点地方需要点思路。
